# Generated by Django 2.2.3 on 2019-07-17 10:10

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CONSTITUEN', models.CharField(max_length=255)),
                ('CONST_CODE', models.FloatField(null=True)),
                ('COUNTY_NAM', models.CharField(max_length=255, null=True)),
                ('Shape_Leng', models.FloatField(null=True)),
                ('Shape_Area', models.FloatField(null=True)),
                ('COUNTY_COD', models.FloatField(null=True)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict, null=True)),
                ('geo', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
